"use client";

import { forwardRef } from "react";

export type ExportItem = {
  name: string;
  scientific: string | null;
  quantity: number;
  note: string | null;
};

type Props = {
  customer: string;
  address?: string | null;
  notes?: string | null;
  items: ExportItem[];
};

export const SelectionExport = forwardRef<HTMLDivElement, Props>(function SelectionExport(
  { customer, address, notes, items },
  ref,
) {
  const date = new Date().toLocaleDateString(undefined, {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <div ref={ref} style={{ width: 800, padding: 40, background: "#ffffff", color: "#111827", fontFamily: "system-ui, -apple-system, sans-serif" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "2px solid #1f7a3a", paddingBottom: 16 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/riversidelogo.png" alt="" width={56} height={56} style={{ objectFit: "contain" }} />
          <div>
            <div style={{ fontSize: 22, fontWeight: 700 }}>Riverside Lawncare</div>
            <div style={{ fontSize: 13, color: "#6b7280" }}>Plant list</div>
          </div>
        </div>
        <div style={{ textAlign: "right", fontSize: 13, color: "#6b7280" }}>{date}</div>
      </div>

      <div style={{ marginTop: 24 }}>
        <div style={{ fontSize: 24, fontWeight: 600 }}>{customer}</div>
        {address && <div style={{ fontSize: 14, color: "#6b7280", marginTop: 2 }}>{address}</div>}
      </div>

      <table style={{ width: "100%", borderCollapse: "collapse", marginTop: 24, fontSize: 14 }}>
        <thead>
          <tr style={{ textAlign: "left", color: "#6b7280", borderBottom: "1px solid #e5e7eb" }}>
            <th style={{ padding: "8px 0", width: 60 }}>Qty</th>
            <th style={{ padding: "8px 0" }}>Plant</th>
            <th style={{ padding: "8px 0" }}>Notes</th>
          </tr>
        </thead>
        <tbody>
          {items.map((it, i) => (
            <tr key={i} style={{ borderBottom: "1px solid #f3f4f6" }}>
              <td style={{ padding: "10px 0", fontWeight: 600 }}>{it.quantity}</td>
              <td style={{ padding: "10px 8px 10px 0" }}>
                <div style={{ fontWeight: 500 }}>{it.name}</div>
                {it.scientific && (
                  <div style={{ fontStyle: "italic", color: "#6b7280", fontSize: 12 }}>{it.scientific}</div>
                )}
              </td>
              <td style={{ padding: "10px 0", color: "#374151" }}>{it.note ?? ""}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {notes && (
        <div style={{ marginTop: 24, padding: 16, background: "#f1faf3", borderRadius: 12, fontSize: 13, color: "#1f2937" }}>
          <div style={{ fontWeight: 600, marginBottom: 4 }}>Project notes</div>
          <div style={{ whiteSpace: "pre-wrap" }}>{notes}</div>
        </div>
      )}

      <div style={{ marginTop: 32, fontSize: 12, color: "#9ca3af" }}>
        Generated by Riverside Lawncare • {date}
      </div>
    </div>
  );
});
